
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://ws/", className = "proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://ws/", className = "proxy.ConvertResponse")
    @Action(input = "http://ws/BanqueService/convertRequest", output = "http://ws/BanqueService/convertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod(operationName = "Getallcompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Getallcompte", targetNamespace = "http://ws/", className = "proxy.Getallcompte")
    @ResponseWrapper(localName = "GetallcompteResponse", targetNamespace = "http://ws/", className = "proxy.GetallcompteResponse")
    @Action(input = "http://ws/BanqueService/GetallcompteRequest", output = "http://ws/BanqueService/GetallcompteResponse")
    public List<Compte> getallcompte();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod(operationName = "Getcompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Getcompte", targetNamespace = "http://ws/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "GetcompteResponse", targetNamespace = "http://ws/", className = "proxy.GetcompteResponse")
    @Action(input = "http://ws/BanqueService/GetcompteRequest", output = "http://ws/BanqueService/GetcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
